spring:
  config:
    activate:
      on-profile: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082

---
spring:
  config:
    activate:
      on-profile: test

  security:
    oauth2:
      resourceserver:
        jwt:
            public-key-location: 'classpath:keys/public_key_rsa.pub'


